-- 입금 계좌와 계좌별 입금 내역을 사용자별로 분리해 저장합니다.
create table public.bank_account (
  id integer generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade default auth.uid(),
  bank_account_number text not null,
  bank_account_name text not null,
  bank text not null,
  bank_code text not null,
  bank_password text not null,
  resident_number text not null
);

comment on table public.bank_account is '사용자별 입금 계좌 정보';
comment on column public.bank_account.id is '입금 계좌 고유 ID';
comment on column public.bank_account.user_id is '계좌를 소유한 Supabase Auth 사용자 ID';
comment on column public.bank_account.bank_account_number is '입금 계좌번호';
comment on column public.bank_account.bank_account_name is '예금주 또는 계좌 표시명';
comment on column public.bank_account.bank is '은행명';
comment on column public.bank_account.bank_code is '은행 코드';
comment on column public.bank_account.bank_password is '계좌 비밀번호 또는 조회용 비밀번호';
comment on column public.bank_account.resident_number is '주민등록번호 등 계좌 인증에 필요한 식별번호';

create index bank_account_user_id_idx on public.bank_account (user_id);

alter table public.bank_account enable row level security;

create policy "bank_account_select_own"
  on public.bank_account
  for select
  to authenticated
  using (auth.uid() = user_id);

create policy "bank_account_insert_own"
  on public.bank_account
  for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "bank_account_update_own"
  on public.bank_account
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "bank_account_delete_own"
  on public.bank_account
  for delete
  to authenticated
  using (auth.uid() = user_id);

create table public.bank_account_deposit (
  id integer generated by default as identity primary key,
  bank_account_id integer not null references public.bank_account (id) on delete cascade,
  "date" date not null,
  counterparty text not null,
  amount integer not null
);

comment on table public.bank_account_deposit is '입금 계좌별 입금 내역';
comment on column public.bank_account_deposit.id is '입금 내역 고유 ID';
comment on column public.bank_account_deposit.bank_account_id is '입금 계좌 ID';
comment on column public.bank_account_deposit."date" is '입금일';
comment on column public.bank_account_deposit.counterparty is '입금 상대방 또는 거래처명';
comment on column public.bank_account_deposit.amount is '입금 금액';

create index bank_account_deposit_bank_account_id_idx
  on public.bank_account_deposit (bank_account_id);

create index bank_account_deposit_bank_account_id_date_idx
  on public.bank_account_deposit (bank_account_id, "date" desc);

alter table public.bank_account_deposit enable row level security;

create policy "bank_account_deposit_select_own"
  on public.bank_account_deposit
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.bank_account as ba
      where ba.id = bank_account_id
        and ba.user_id = auth.uid()
    )
  );

create policy "bank_account_deposit_insert_own"
  on public.bank_account_deposit
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.bank_account as ba
      where ba.id = bank_account_id
        and ba.user_id = auth.uid()
    )
  );

create policy "bank_account_deposit_update_own"
  on public.bank_account_deposit
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.bank_account as ba
      where ba.id = bank_account_id
        and ba.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.bank_account as ba
      where ba.id = bank_account_id
        and ba.user_id = auth.uid()
    )
  );

create policy "bank_account_deposit_delete_own"
  on public.bank_account_deposit
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.bank_account as ba
      where ba.id = bank_account_id
        and ba.user_id = auth.uid()
    )
  );
